"""
OCR Service — EasyOCR-based handwriting/text recognition with PDF generation.

Accepts image files (JPG, JPEG, PNG), extracts text using EasyOCR,
and generates a clean PDF containing the extracted text.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# Lazy-loaded EasyOCR reader (heavy model, ~200MB on first download)
_reader = None

IMAGE_EXTENSIONS = {"jpg", "jpeg", "png"}
MAX_IMAGE_SIZE = 10 * 1024 * 1024  # 10MB per image
OCR_LANGUAGES = ["en", "hi"]  # English + Hindi by default


def _get_reader():
    """
    Lazy-initialise the EasyOCR reader so the heavy model is only loaded
    once per process and only when actually needed.
    """
    global _reader
    if _reader is None:
        try:
            import easyocr
        except ImportError:
            raise ImportError(
                "easyocr is not installed. Run: pip install easyocr"
            )
        logger.info("Loading EasyOCR reader for languages: %s", OCR_LANGUAGES)
        _reader = easyocr.Reader(OCR_LANGUAGES, gpu=False)
        logger.info("EasyOCR reader loaded successfully")
    return _reader


def extract_text_from_image(image_path: str) -> str:
    """
    Run OCR on a single image and return the extracted text.

    Args:
        image_path: Absolute path to the image file.

    Returns:
        Extracted text as a single string with line breaks preserved.
    """
    reader = _get_reader()
    results = reader.readtext(image_path, detail=0, paragraph=True)
    text = "\n".join(results)
    logger.info(
        "OCR extracted %d characters from %s",
        len(text),
        Path(image_path).name,
    )
    return text


def image_to_pdf(
    image_path: str,
    output_path: str,
    *,
    title: Optional[str] = None,
) -> str:
    """
    Convert an image to a PDF containing the OCR-extracted text.

    The generated PDF has:
    - A header line with the original filename and a title (if given)
    - The full extracted text formatted in a readable layout

    Args:
        image_path: Absolute path to the source image.
        output_path: Absolute path for the generated PDF.
        title: Optional title to display at the top of the PDF.

    Returns:
        The output_path on success.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        raise ImportError("fpdf2 is not installed. Run: pip install fpdf2")

    # Extract text via OCR
    extracted_text = extract_text_from_image(image_path)
    if not extracted_text.strip():
        extracted_text = "(No text could be extracted from this image.)"

    source_name = Path(image_path).name

    # Build PDF
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Use a built-in font that supports basic Latin characters.
    # For full Hindi/Devanagari rendering a TTF font would be needed;
    # the textual content is still preserved in the PDF even if glyphs
    # fall back to replacement characters on some viewers.
    pdf.set_font("Helvetica", "B", 14)
    header = title if title else f"OCR: {source_name}"
    pdf.cell(0, 10, header, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(
        0,
        6,
        f"Source: {source_name} | Generated by VidyaOS OCR",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(4)

    # Body text
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 11)

    for line in extracted_text.split("\n"):
        line = line.strip()
        if not line:
            pdf.ln(4)
            continue
        # Encode to latin-1 safe subset for built-in fonts
        safe_line = line.encode("latin-1", errors="replace").decode("latin-1")
        pdf.multi_cell(0, 6, safe_line)

    pdf.output(output_path)
    logger.info("Generated PDF at %s (%d chars)", output_path, len(extracted_text))
    return output_path


def is_image_file(filename: str) -> bool:
    """Check whether the filename has an image extension."""
    ext = filename.rsplit(".", 1)[-1].lower() if "." in filename else ""
    return ext in IMAGE_EXTENSIONS


def validate_image_size(content: bytes) -> None:
    """Raise ValueError if the image content exceeds the size limit."""
    if len(content) > MAX_IMAGE_SIZE:
        raise ValueError(
            f"Image exceeds {MAX_IMAGE_SIZE // (1024 * 1024)}MB limit."
        )
